development:
  adapter: postgresql
  database: play_it_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: play_it_test
  pool: 5
  timeout: 10000

production:
  adapter: postgresql
  database: play-it_prod
  pool: 5
  timeout: 5000